File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete


File "/usr/local/lib/python3.12/site-packages/uvicorn/server.py", line 69, in serve


await self._serve(sockets)


File "/usr/local/lib/python3.12/site-packages/uvicorn/server.py", line 76, in _serve


config.load()


File "/usr/local/lib/python3.12/site-packages/uvicorn/config.py", line 434, in load


self.loaded_app = import_from_string(self.app)


^^^^^^^^^^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/uvicorn/importer.py", line 19, in import_from_string


module = importlib.import_module(module_str)


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module


return _bootstrap._gcd_import(name[level:], package, level)


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


File "<frozen importlib._bootstrap>", line 1387, in _gcd_import


File "<frozen importlib._bootstrap>", line 1360, in _find_and_load


File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked


File "<frozen importlib._bootstrap>", line 935, in _load_unlocked


File "<frozen importlib._bootstrap_external>", line 999, in exec_module


File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed


File "/app/main.py", line 10, in <module>


from app.api.v1 import api_router


File "/app/app/__init__.py", line 3, in <module>


from app.core.config import settings


File "/app/app/core/__init__.py", line 3, in <module>


from app.core.config import settings


File "/app/app/core/config.py", line 112, in <module>


settings = get_settings()


^^^^^^^^^^^^^^


File "/app/app/core/config.py", line 108, in get_settings


return Settings()


^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/pydantic_settings/main.py", line 153, in __init__


**__pydantic_self__._settings_build_values(


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/pydantic_settings/main.py", line 357, in _settings_build_values


source_state = source()


^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/pydantic_settings/sources.py", line 973, in __call__


data: dict[str, Any] = super().__call__()


^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/pydantic_settings/sources.py", line 547, in __call__


raise SettingsError(


pydantic_settings.sources.SettingsError: error parsing value for field "ALLOWED_ORIGINS" from source "DotEnvSettingsSource"

