Waiting for PostgreSQL...


db:5432 - accepting connections


PostgreSQL is ready!


Running migrations...


Traceback (most recent call last):


File "/usr/local/lib/python3.12/site-packages/django/db/models/utils.py", line 15, in make_model_tuple


app_label, model_name = model.split(".")


^^^^^^^^^^^^^^^^^^^^^


ValueError: too many values to unpack (expected 2)




During handling of the above exception, another exception occurred:




Traceback (most recent call last):


File "/app/manage.py", line 22, in <module>


main()


File "/app/manage.py", line 18, in main


execute_from_command_line(sys.argv)


File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line


utility.execute()


File "/usr/local/lib/python3.12/site-packages/django/core/management/__init__.py", line 416, in execute


django.setup()


File "/usr/local/lib/python3.12/site-packages/django/__init__.py", line 24, in setup


apps.populate(settings.INSTALLED_APPS)


File "/usr/local/lib/python3.12/site-packages/django/apps/registry.py", line 116, in populate


app_config.import_models()


File "/usr/local/lib/python3.12/site-packages/django/apps/config.py", line 269, in import_models


self.models_module = import_module(models_module_name)


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module


return _bootstrap._gcd_import(name[level:], package, level)


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


File "<frozen importlib._bootstrap>", line 1387, in _gcd_import


File "<frozen importlib._bootstrap>", line 1360, in _find_and_load


File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked


File "<frozen importlib._bootstrap>", line 935, in _load_unlocked


File "<frozen importlib._bootstrap_external>", line 999, in exec_module


File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed


File "/usr/local/lib/python3.12/site-packages/django/contrib/admin/models.py", line 106, in <module>


class LogEntry(models.Model):


File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 196, in __new__


new_class.add_to_class(obj_name, obj)


File "/usr/local/lib/python3.12/site-packages/django/db/models/base.py", line 373, in add_to_class


value.contribute_to_class(cls, name)


File "/usr/local/lib/python3.12/site-packages/django/db/models/fields/related.py", line 928, in contribute_to_class


super().contribute_to_class(cls, name, private_only=private_only, **kwargs)


File "/usr/local/lib/python3.12/site-packages/django/db/models/fields/related.py", line 380, in contribute_to_class


lazy_related_operation(


File "/usr/local/lib/python3.12/site-packages/django/db/models/fields/related.py", line 88, in lazy_related_operation


return apps.lazy_model_operation(partial(function, **kwargs), *model_keys)


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/django/db/models/fields/related.py", line 86, in <genexpr>


model_keys = (make_model_tuple(m) for m in models)


^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/django/db/models/utils.py", line 22, in make_model_tuple