django_celery_beat
self.worker_fixup.validate_models()


File "/usr/local/lib/python3.12/site-packages/celery/fixups/django.py", line 141, in validate_models


run_checks()


File "/usr/local/lib/python3.12/site-packages/django/core/checks/registry.py", line 89, in run_checks


new_errors = check(app_configs=app_configs, databases=databases)


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/debug_toolbar/apps.py", line 225, in debug_toolbar_installed_when_running_tests_check


reverse(f"{APP_NAME}:render_panel")


File "/usr/local/lib/python3.12/site-packages/django/urls/base.py", line 64, in reverse


app_list = resolver.app_dict[ns]


^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/django/urls/resolvers.py", line 637, in app_dict


self._populate()


File "/usr/local/lib/python3.12/site-packages/django/urls/resolvers.py", line 548, in _populate


for url_pattern in reversed(self.url_patterns):


^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__


res = instance.__dict__[self.name] = self.func(instance)


^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/django/urls/resolvers.py", line 718, in url_patterns


patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)


^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__


res = instance.__dict__[self.name] = self.func(instance)


^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/django/urls/resolvers.py", line 711, in urlconf_module


return import_module(self.urlconf_name)


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module


return _bootstrap._gcd_import(name[level:], package, level)


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


File "<frozen importlib._bootstrap>", line 1387, in _gcd_import


File "<frozen importlib._bootstrap>", line 1360, in _find_and_load


File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked


File "<frozen importlib._bootstrap>", line 935, in _load_unlocked


File "<frozen importlib._bootstrap_external>", line 999, in exec_module


File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed


File "/app/config/urls.py", line 24, in <module>


path('api/sample/', include('apps.sample.urls')),


^^^^^^^^^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/django/urls/conf.py", line 39, in include


urlconf_module = import_module(urlconf_module)


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module


return _bootstrap._gcd_import(name[level:], package, level)


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


File "<frozen importlib._bootstrap>", line 1387, in _gcd_import


File "<frozen importlib._bootstrap>", line 1360, in _find_and_load


File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked


File "<frozen importlib._bootstrap>", line 935, in _load_unlocked


File "<frozen importlib._bootstrap_external>", line 999, in exec_module


File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed


File "/app/apps/sample/urls.py", line 12, in <module>


from .views import PostViewSet, CategoryViewSet


ImportError: cannot import name 'PostViewSet' from 'apps.sample.views' (/app/apps/sample/views/__init__.py)





django_celery_worker
File "/usr/local/lib/python3.12/site-packages/celery/bin/worker.py", line 348, in worker


worker = app.Worker(


^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/celery/worker/worker.py", line 94, in __init__


self.app.loader.init_worker()


File "/usr/local/lib/python3.12/site-packages/celery/loaders/base.py", line 110, in init_worker


self.import_default_modules()


File "/usr/local/lib/python3.12/site-packages/celery/loaders/base.py", line 104, in import_default_modules


raise response


File "/usr/local/lib/python3.12/site-packages/celery/utils/dispatch/signal.py", line 280, in send


response = receiver(signal=self, sender=sender, **named)


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/celery/fixups/django.py", line 101, in on_import_modules


self.worker_fixup.validate_models()


File "/usr/local/lib/python3.12/site-packages/celery/fixups/django.py", line 141, in validate_models


run_checks()


File "/usr/local/lib/python3.12/site-packages/django/core/checks/registry.py", line 89, in run_checks


new_errors = check(app_configs=app_configs, databases=databases)


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/django/core/checks/urls.py", line 138, in check_custom_error_handlers


path = getattr(resolver.urlconf_module, "handler%s" % status_code)


^^^^^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/django/utils/functional.py", line 47, in __get__


res = instance.__dict__[self.name] = self.func(instance)


^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/django/urls/resolvers.py", line 711, in urlconf_module


return import_module(self.urlconf_name)


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module


return _bootstrap._gcd_import(name[level:], package, level)


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


File "<frozen importlib._bootstrap>", line 1387, in _gcd_import


File "<frozen importlib._bootstrap>", line 1360, in _find_and_load


File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked


File "<frozen importlib._bootstrap>", line 935, in _load_unlocked


File "<frozen importlib._bootstrap_external>", line 999, in exec_module


File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed


File "/app/config/urls.py", line 24, in <module>


path('api/sample/', include('apps.sample.urls')),


^^^^^^^^^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/site-packages/django/urls/conf.py", line 39, in include


urlconf_module = import_module(urlconf_module)


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module


return _bootstrap._gcd_import(name[level:], package, level)


^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


File "<frozen importlib._bootstrap>", line 1387, in _gcd_import


File "<frozen importlib._bootstrap>", line 1360, in _find_and_load


File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked


File "<frozen importlib._bootstrap>", line 935, in _load_unlocked


File "<frozen importlib._bootstrap_external>", line 999, in exec_module


File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed


File "/app/apps/sample/urls.py", line 12, in <module>


from .views import PostViewSet, CategoryViewSet


ImportError: cannot import name 'PostViewSet' from 'apps.sample.views' (/app/apps/sample/views/__init__.py)